### PR TITLE
Updated tutorials

### PR DESCRIPTION
**Pull request by kjang96**
Updated tutorials as per the Flow repo.

### CODE REVIEW

**Comment by ashkan-software** [comment]
Thanks @kjang96! Could you please make sure the links work? It seems some links are old (e.g. link for Visualizing Tutorial) and they need to be updated

**Comment by kjang96** [comment]
@ashkan-software  Done!

**Comment by ashkan-software** [comment]
Can someone merge this?

**Comment by eugenevinitsky** [comment]
Stale.

**Pull request closed without merging**
